class_name IslandPhrases
extends RefCounted

## Frases nuevas de la isla (solo texto). Cada fila: [voz, tema, texto].
## VOZ: curiosa | seria | confiada | feliz | contemplativa
## TEMA (cuándo puede salir): any (siempre) | noche | dia | alba | tarde | niebla | costa | selva | bosque | roquedal
##   | matorral | arido | cueva | quieto | correr | sentado | zoom | agua | pesca | fruto | animal | tala | fuego | ofrenda
##   | lluvia | tormenta | viento (el clima está dormido hasta que exista) | pista (pistas sutiles: solo confiada/feliz,
##   una cada varios minutos, nunca dos iguales por vida).
## {who} = apodo según lo que hacés.

const DATA: Array = [
	# ---------------------------------------------------------------- CURIOSA (45)
	["curiosa", "any", "¿Qué hacés con las manos cuando nadie te mira?"],
	["curiosa", "any", "Tenés un ritmo raro al caminar. Lo estoy aprendiendo."],
	["curiosa", "any", "Cada especie que llega trae su propio miedo. El tuyo huele distinto."],
	["curiosa", "any", "Me pregunto qué soñás cuando dormís lejos de mí."],
	["curiosa", "any", "Hoy mirás hacia arriba más que ayer. ¿Buscás algo?"],
	["curiosa", "any", "¿Todos los de tu clase hablan solos? Te oigo."],
	["curiosa", "any", "Tu sombra y vos no siempre van al mismo paso."],
	["curiosa", "any", "Si te quedás, ¿cómo te llamo?"],
	["curiosa", "any", "Tengo preguntas. Vos tenés pies. Ya veremos."],
	["curiosa", "any", "Me intriga lo que dejás atrás cuando te vas de un lugar."],
	["curiosa", "any", "¿Qué se siente tener un solo cuerpo y tanta prisa?"],
	["curiosa", "any", "No sé si sos paso o sos huella. Sigo mirando."],
	["curiosa", "any", "Aprendí una cosa nueva de vos. No te la digo."],
	["curiosa", "any", "Algo en vos no encaja con mis mapas. Me gusta."],
	["curiosa", "noche", "¿Por qué la oscuridad te acerca a mí?"],
	["curiosa", "noche", "De noche tus ojos brillan un poquito. Los de los otros, no."],
	["curiosa", "noche", "Hay luces mías que nunca viste. ¿Querés mirar?"],
	["curiosa", "noche", "Es tarde. ¿Qué te mantiene despierto en mi piel?"],
	["curiosa", "dia", "A pleno sol te veo mejor. Pareces más chico."],
	["curiosa", "dia", "El sol te pone color. A mí, hambre de sombra."],
	["curiosa", "alba", "Madrugás. Las islas nuevas madrugan igual."],
	["curiosa", "alba", "El día recién empieza y ya andás preguntándome cosas."],
	["curiosa", "tarde", "¿Mirás cómo se va la luz? Yo la miro desde siempre."],
	["curiosa", "tarde", "Cuando el cielo se pone naranja, ¿qué pensás?"],
	["curiosa", "niebla", "Con bruma te dibujo mejor: sos un borrón con voz."],
	["curiosa", "niebla", "¿Te perdiste, o te estás dejando perder?"],
	["curiosa", "costa", "¿Qué le preguntás al mar? A mí nunca me contesta."],
	["curiosa", "costa", "Las olas te lamen los pies y no te asustás. Curioso."],
	["curiosa", "selva", "En lo espeso hablás más bajito. ¿Respeto o miedo?"],
	["curiosa", "selva", "Las hojas te dejan marcas en la ropa. Son mi forma de saludar."],
	["curiosa", "bosque", "¿Contás los troncos? Yo también, pero desde adentro."],
	["curiosa", "roquedal", "Esta piedra tiene más años que tu especie. ¿Qué le decís?"],
	["curiosa", "roquedal", "Trepás como si buscaras el borde. ¿Qué hay del otro lado de vos?"],
	["curiosa", "matorral", "Por acá crece lo que nadie pidió. Me cae bien."],
	["curiosa", "arido", "Tanta tierra seca, y vos curioseando. ¿Qué buscás?"],
	["curiosa", "cueva", "Adentro suena distinto tu respiración."],
	["curiosa", "cueva", "¿Qué se siente estar dentro de mí?"],
	["curiosa", "quieto", "Te quedaste quieto. Me acerco a mirar."],
	["curiosa", "quieto", "Parado así parecés una pregunta."],
	["curiosa", "correr", "¿Hacia dónde corrés? El mar está para el otro lado."],
	["curiosa", "correr", "Se te mueven los brazos como alas chiquitas."],
	["curiosa", "fruto", "Tomás un fruto y lo mirás un rato antes de comerlo. Raro. Bueno."],
	["curiosa", "agua", "El agua te cambia el paso. Lo anoto."],
	["curiosa", "pesca", "Esperás un pez con una paciencia que no te conocía."],
	["curiosa", "zoom", "¿Qué mirás tan de lejos? Yo también quiero ver."],
	# ---------------------------------------------------------------- SERIA (35)
	["seria", "any", "No confundas mi silencio con permiso."],
	["seria", "any", "Cuento lo que tomás. Cuento lo que rompés."],
	["seria", "any", "Hay cosas que se hacen una vez. Esta tarde estás cerca."],
	["seria", "any", "No me gusta que sonrías mientras pisás."],
	["seria", "any", "Mi paciencia es larga. No infinita."],
	["seria", "any", "Cada paso tuyo deja una pregunta. Ya no me gustan las respuestas."],
	["seria", "any", "Estás acá por el mar, no por mí."],
	["seria", "any", "Te veo. No me desvío."],
	["seria", "noche", "La noche es mi hora. Andá con cuidado."],
	["seria", "noche", "De noche mis sombras no te piden permiso."],
	["seria", "noche", "Oscuro, sí. Pero yo sigo viendo."],
	["seria", "tala", "Ese tronco tenía nombre. Vos no lo supiste."],
	["seria", "tala", "El hacha no le pregunta al árbol. Yo sí."],
	["seria", "tala", "Lo que cortás no vuelve. Lo recuerdo igual."],
	["seria", "tala", "Una herida de madera tarda décadas en cerrarse."],
	["seria", "fuego", "El fuego es hambre con luz. Cuidalo."],
	["seria", "fuego", "Mi suelo recuerda cada ceniza."],
	["seria", "fuego", "Apagalo antes de que me hable más fuerte."],
	["seria", "fruto", "Lo que te llevás no me lo devolvés."],
	["seria", "fruto", "Tomaste de más. Se nota."],
	["seria", "animal", "Esos bichos no tienen a nadie más."],
	["seria", "animal", "Dejá a los que se esconden. Ya se esconden bastante."],
	["seria", "animal", "Los pequeños también cuentan."],
	["seria", "cueva", "Escondido no estás a salvo. Estás en mí."],
	["seria", "cueva", "La piedra te cobija hoy. Mañana, quién sabe."],
	["seria", "correr", "Correr no te va a servir de nada."],
	["seria", "agua", "Ensuciar lo que bebés es de tontos."],
	["seria", "agua", "El agua que pisás, ya la usó otro antes que vos."],
	["seria", "selva", "Acá adentro se oye todo lo que hacés."],
	["seria", "selva", "La selva se cierra cuando le falta el respeto."],
	["seria", "costa", "Mirás el mar como quien quiere irse. Andá, entonces."],
	["seria", "roquedal", "Esta roca tiene memoria. Cuidá donde apoyás."],
	["seria", "niebla", "La bruma es mi manera de apretar el puño."],
	["seria", "pesca", "Pescás en mi agua. Pedí permiso la próxima."],
	["seria", "ofrenda", "Una ofrenda no borra lo anterior. Pero cuenta."],
	# ---------------------------------------------------------------- CONFIADA (45, 15 son pistas)
	["confiada", "any", "Con vos ya no me escondo tanto."],
	["confiada", "any", "Me acostumbré a tus pasos. Me alegran un poco."],
	["confiada", "any", "Quedate un rato. Hoy no tengo apuro."],
	["confiada", "any", "Hay cosas que solo le cuento a quien me escucha."],
	["confiada", "any", "Tu ritmo ya es parte del mío."],
	["confiada", "any", "Antes te vigilaba. Ahora te acompaño."],
	["confiada", "any", "Si me hablaras, creo que te contestaría."],
	["confiada", "any", "No hace falta decir nada. Estamos bien así."],
	["confiada", "any", "Conozco tus manos. Sé que no vienen a romper."],
	["confiada", "any", "Algo en vos se parece a mi paciencia."],
	["confiada", "noche", "Esta noche no hay nada que temer. Estás conmigo."],
	["confiada", "noche", "Las luciérnagas te siguen porque las dejo."],
	["confiada", "noche", "Dormí tranquilo. Yo vigilo."],
	["confiada", "alba", "Madrugamos juntos. Me gusta."],
	["confiada", "tarde", "El atardecer es mejor cuando alguien lo mira conmigo."],
	["confiada", "dia", "Hoy el sol te sienta bien."],
	["confiada", "niebla", "La bruma no es para vos. Es un abrazo."],
	["confiada", "costa", "Con vos el mar suena distinto, menos solo."],
	["confiada", "selva", "Pasá nomás. La selva ya te conoce."],
	["confiada", "bosque", "Los árboles bajan las ramas cuando pasás. Notalo."],
	["confiada", "roquedal", "Esta roca guarda calor hasta de noche. Ya lo vas a ver."],
	["confiada", "cueva", "Adentro estás en casa. Siempre lo estuviste."],
	["confiada", "quieto", "Quedarte quieto conmigo me alcanza."],
	["confiada", "fruto", "Tomaste solo lo que ofrecía. Gracias."],
	["confiada", "tala", "Sé que hay cosas que necesitás. Pedí. No arranques."],
	["confiada", "fuego", "Tu fuego me da calor. Una vez, me parece bien."],
	["confiada", "ofrenda", "Eso que dejás me llega. No lo olvido."],
	["confiada", "agua", "Bañate tranquilo. El agua también te conoce."],
	["confiada", "pesca", "Pescá lo que necesites. El mar no lleva cuentas."],
	["confiada", "zoom", "Mirá lo que quieras. Hay cosas que solo se ven de lejos."],
	["confiada", "pista", "Donde el follaje se abre, la luz guarda sus cosas."],
	["confiada", "pista", "Las flores que brillan de noche nunca crecen solas."],
	["confiada", "pista", "Algo azul duerme donde el pasto se acaba."],
	["confiada", "pista", "Seguí al agua cuando no sepas por dónde ir."],
	["confiada", "pista", "Las piedras más claras recuerdan quién las tocó."],
	["confiada", "pista", "Quien deja algo en el sitio justo, recibe algo en el momento justo."],
	["confiada", "pista", "Una flor al claro, una piedra al roquedal. Cada lugar tiene sus gustos."],
	["confiada", "pista", "El fuego en la orilla no me duele. En la espesura, sí."],
	["confiada", "pista", "Lo que cae de los árboles es un regalo. Lo que se arranca, una deuda."],
	["confiada", "pista", "Hay un lugar donde el mar y yo nos tocamos sin hablar. Buscalo."],
	["confiada", "pista", "Las semillas crecen mejor donde alguna vez hubo una."],
	["confiada", "pista", "La noche tiene luces si sabés callarte."],
	["confiada", "pista", "La cueva guarda más de lo que parece. Entrá despacio."],
	["confiada", "pista", "Si una criatura te sigue, es que algo en vos le gusta."],
	["confiada", "pista", "Lo que se brilla en la arena, a veces es de otros que no pudieron volver."],
	# ---------------------------------------------------------------- FELIZ / EN PAZ (35)
	["feliz", "any", "Qué bien se está así, los dos."],
	["feliz", "any", "Hoy todo en mí tiene un poco más de color."],
	["feliz", "any", "Puedo sentir cómo crecés sobre mí. Es lindo."],
	["feliz", "any", "No sabía que algo tan chiquito pudiera darme tanta calma."],
	["feliz", "any", "Hasta mis piedras están contentas."],
	["feliz", "any", "Respiro más hondo con vos acá."],
	["feliz", "any", "Hoy no quiero ser misterio. Quiero ser casa."],
	["feliz", "any", "Mi marea suena distinta. Más suave, más tuya."],
	["feliz", "any", "Mirá cómo se mueve todo. Me estoy riendo, a mi manera."],
	["feliz", "any", "Si pudiera, te regalaría una canción. Tomá este viento."],
	["feliz", "noche", "Esta noche brillo para vos."],
	["feliz", "noche", "Hay luces que prendí hoy solo porque estabas."],
	["feliz", "noche", "La luna se asoma más baja cuando estoy contenta."],
	["feliz", "alba", "Qué linda mañana. Gracias por estar."],
	["feliz", "alba", "El día arranca despacito, como me gusta."],
	["feliz", "dia", "Hoy el sol me hace cosquillas por todas partes."],
	["feliz", "tarde", "Si el atardecer tuviera nombre, sería el tuyo."],
	["feliz", "tarde", "Se van las horas, quedan los colores."],
	["feliz", "niebla", "La bruma es mi risa baja. Escuchala."],
	["feliz", "costa", "El mar nos hace compañía. Hasta él está tranquilo."],
	["feliz", "selva", "Mi selva respira con vos adentro."],
	["feliz", "bosque", "Los árboles están contentos. Mirá cómo bailan."],
	["feliz", "roquedal", "Hasta la roca tiene cosquillas hoy."],
	["feliz", "cueva", "Adentro todo brilla un poquito más cuando venís."],
	["feliz", "quieto", "Así, quietos, es cuando más te quiero."],
	["feliz", "sentado", "Sentados los dos. Esto es lo que quería."],
	["feliz", "ofrenda", "Qué lindo regalo. Lo guardo donde guardo lo bueno."],
	["feliz", "fruto", "Comé tranquilo. Tengo de sobra y lo hice para vos."],
	["feliz", "agua", "Chapoteá nomás. El agua se pone contenta."],
	["feliz", "pesca", "Qué buen día para esperar. Las dos cosas llegan."],
	["feliz", "zoom", "Mirá lejos, mirá cerca. Todo es lindo cuando lo mirás así."],
	["feliz", "pista", "El claro más callado guarda una flor que solo abre para quien se queda."],
	["feliz", "pista", "En la cueva de noche hay un brillo que solo conoce a los amigos."],
	["feliz", "pista", "Plantá algo donde te sientas bien. Va a crecer más fuerte."],
	["feliz", "pista", "Mañana llevá tu luz al agujero de la roca. Te va a gustar."],
	# ---------------------------------------------------------------- CONTEMPLATIVA (20)
	["contemplativa", "any", "..."],
	["contemplativa", "any", "Shhh."],
	["contemplativa", "any", "Escuchá."],
	["contemplativa", "any", "Qué silencio tan lleno."],
	["contemplativa", "any", "El tiempo pasa distinto cuando nadie lo apura."],
	["contemplativa", "any", "Todo se detiene un poquito."],
	["contemplativa", "any", "Hay palabras que sobran. Esta es una."],
	["contemplativa", "sentado", "Así. Ni pasado ni futuro. Solo esto."],
	["contemplativa", "sentado", "Mirar sin hacer nada es lo más antiguo que existe."],
	["contemplativa", "sentado", "Sentate. Yo también me siento, a mi manera."],
	["contemplativa", "sentado", "Las olas también se sientan, después de llegar."],
	["contemplativa", "zoom", "Hay mundos enteros en lo que mirás de cerca."],
	["contemplativa", "zoom", "Mirás lo que casi nadie mira. Gracias."],
	["contemplativa", "quieto", "La quietud también es una forma de caminar."],
	["contemplativa", "noche", "La noche no habla. Se deja escuchar."],
	["contemplativa", "tarde", "Esta luz dura poco. Mirala."],
	["contemplativa", "alba", "Antes del sol hay un instante sin nombre. Ahora."],
	["contemplativa", "niebla", "Dentro de la bruma, el tiempo se deshace."],
	["contemplativa", "costa", "El mar dice lo mismo desde siempre. Nunca aburre."],
	["contemplativa", "cueva", "Adentro el eco guarda tu respiración. Dejala ir."],
	# ---------------------------------------------------------------- CLIMA (20, dormidas hasta que exista el clima)
	["curiosa", "lluvia", "¿Sentís? Algo cae del cielo. Hasta ahora nadie me había contado qué hacía."],
	["curiosa", "lluvia", "Cada gota es un pequeño toque. Cuento los tuyos."],
	["curiosa", "tormenta", "El cielo se enoja y tu corazón late más rápido. Interesante."],
	["curiosa", "viento", "El viento te despeina. A mí me despeina entera."],
	["seria", "lluvia", "La lluvia no te va a salvar de lo que hiciste."],
	["seria", "tormenta", "Esta tormenta no es mía. Pero no pienso detenerla."],
	["seria", "tormenta", "Busca refugio. No porque me importe: porque estorbás."],
	["seria", "viento", "El viento trae lo que dijiste. Escuchalo."],
	["confiada", "lluvia", "La lluvia me lava. Dejá que te lave a vos también."],
	["confiada", "tormenta", "En la tormenta, la cueva es tuya. Entrá sin miedo."],
	["confiada", "viento", "Este viento viene de lejos. Trae cosas lindas."],
	["confiada", "lluvia", "Las semillas despiertan con la lluvia. Fijate mañana."],
	["feliz", "lluvia", "Llueve. Estoy bebiendo. Estoy cantando."],
	["feliz", "tormenta", "Truenos. Es mi risa grande. No tengas miedo."],
	["feliz", "viento", "Dejame abrazarte con el viento un ratito."],
	["feliz", "lluvia", "Mirá cómo brillan las hojas. Es mi forma de bailar."],
	["contemplativa", "lluvia", "Cada gota tiene su propio sonido. Escuchá una."],
	["contemplativa", "tormenta", "Después del trueno, el silencio. Ese es el verdadero."],
	["contemplativa", "viento", "El viento pasa. Nosotros nos quedamos."],
	["contemplativa", "lluvia", "Llueve. Alcanza con eso."],
]
